server:
  port: 8083
  servlet:
    context-path: /

spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore_customer_db
    username: postgres
    password: quanghieu2512
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  jackson:
    default-property-inclusion: non_null

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.bookstore.customerservice: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.web: INFO