apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  namespace: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
      - name: search-service
        image: bookstore/search-service:latest
        ports:
        - containerPort: 8087
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: bookstore-config
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: bootstrap-servers
        - name: ELASTICSEARCH_HOST
          valueFrom:
            configMapKeyRef:
              name: elasticsearch-config
              key: host
        - name: ELASTICSEARCH_PORT
          valueFrom:
            configMapKeyRef:
              name: elasticsearch-config
              key: port
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8087
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8087
          initialDelaySeconds: 60
          periodSeconds: 15
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: bookstore
spec:
  selector:
    app: search-service
  ports:
  - port: 8087
    targetPort: 8087
  type: ClusterIP