apiVersion: v1
kind: ConfigMap
metadata:
  name: bookstore-config
  namespace: bookstore
data:
  SPRING_PROFILES_ACTIVE: "prod"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: bookstore
data:
  host: postgres
  auth-database: auth_db
  book-database: book_db
  customer-database: customer_db
  order-database: order_db
  inventory-database: inventory_db
  payment-database: payment_db
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: bookstore
data:
  bootstrap-servers: kafka:9092
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: bookstore
data:
  host: elasticsearch
  port: "9200"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: bookstore
data:
  host: redis
  port: "6379"