apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: bookstore
type: Opaque
data:
  username: cG9zdGdyZXM=  # postgres (base64 encoded)
  password: cG9zdGdyZXM=  # postgres (base64 encoded)
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secrets
  namespace: bookstore
type: Opaque
data:
  secret-key: c2VjcmV0LWtleS1mb3ItYm9va3N0b3JlLWp3dC10b2tlbg==  # secret-key-for-bookstore-jwt-token (base64 encoded)