server:
  port: 8082

spring:
  application:
    name: order-service

  cloud:
    config:
      enabled: false
      uri: ${CONFIG_SERVER_URL:http://localhost:8888}
      fail-fast: false
      retry:
        initial-interval: 1000
        max-interval: 2000
        max-attempts: 5

  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore_book_db
    username: postgres
    password: quanghieu2512
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: order-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.bookstore.*
    topic:
      order-created: order-created
      order-status-changed: order-status-changed
      payment-completed: payment-completed

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      bookService:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    com.bookstore.orderservice: INFO
    org.springframework.web: INFO
    org.hibernate: ERROR