version: '3.8'

services:
  # API Gateway
  api-gateway:
    build: 
      context: ./api-gateway
      dockerfile: Dockerfile.dev
    container_name: api-gateway-dev
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - AUTH_SERVICE_URL=http://auth-service:8081
      - BOOK_SERVICE_URL=http://book-service:8082
      - ORDER_SERVICE_URL=http://order-service:8083
      - CUSTOMER_SERVICE_URL=http://customer-service:8084
      - INVENTORY_SERVICE_URL=http://inventory-service:8085
      - PAYMENT_SERVICE_URL=http://payment-service:8086
      - SEARCH_SERVICE_URL=http://search-service:8087
    volumes:
      - ./api-gateway:/app
      - ~/.m2:/root/.m2
    depends_on:
      - auth-service
      - book-service
      - order-service
      - customer-service
      - inventory-service
      - payment-service
      - search-service
    networks:
      - bookstore-network-dev

  # Authentication Service
  auth-service:
    build: 
      context: ./auth-service
      dockerfile: Dockerfile.dev
    container_name: auth-service-dev
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/auth_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    volumes:
      - ./auth-service:/app
      - ~/.m2:/root/.m2
    depends_on:
      - postgres
    networks:
      - bookstore-network-dev

  # Book Service
  book-service:
    build: 
      context: ./book-service
      dockerfile: Dockerfile.dev
    container_name: book-service-dev
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/book_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    volumes:
      - ./book-service:/app
      - ~/.m2:/root/.m2
    depends_on:
      - postgres
      - kafka
      - redis
    networks:
      - bookstore-network-dev

  # Order Service
  order-service:
    build: 
      context: ./order-service
      dockerfile: Dockerfile.dev
    container_name: order-service-dev
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/order_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - BOOK_SERVICE_URL=http://book-service:8082
      - CUSTOMER_SERVICE_URL=http://customer-service:8084
      - INVENTORY_SERVICE_URL=http://inventory-service:8085
    volumes:
      - ./order-service:/app
      - ~/.m2:/root/.m2
    depends_on:
      - postgres
      - kafka
    networks:
      - bookstore-network-dev

  # Customer Service
  customer-service:
    build: 
      context: ./customer-service
      dockerfile: Dockerfile.dev
    container_name: customer-service-dev
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/customer_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    volumes:
      - ./customer-service:/app
      - ~/.m2:/root/.m2
    depends_on:
      - postgres
    networks:
      - bookstore-network-dev

  # Inventory Service
  inventory-service:
    build: 
      context: ./inventory-service
      dockerfile: Dockerfile.dev
    container_name: inventory-service-dev
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/inventory_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - BOOK_SERVICE_URL=http://book-service:8082
    volumes:
      - ./inventory-service:/app
      - ~/.m2:/root/.m2
    depends_on:
      - postgres
      - kafka
    networks:
      - bookstore-network-dev

  # Payment Service
  payment-service:
    build: 
      context: ./payment-service
      dockerfile: Dockerfile.dev
    container_name: payment-service-dev
    ports:
      - "8086:8086"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/payment_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - ORDER_SERVICE_URL=http://order-service:8083
    volumes:
      - ./payment-service:/app
      - ~/.m2:/root/.m2
    depends_on:
      - postgres
      - kafka
    networks:
      - bookstore-network-dev

  # Search Service
  search-service:
    build: 
      context: ./search-service
      dockerfile: Dockerfile.dev
    container_name: search-service-dev
    ports:
      - "8087:8087"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
    volumes:
      - ./search-service:/app
      - ~/.m2:/root/.m2
    depends_on:
      - elasticsearch
      - kafka
    networks:
      - bookstore-network-dev

  # React frontend (if needed)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8080
    networks:
      - bookstore-network-dev

networks:
  bookstore-network-dev:
    driver: bridge

# Using volumes from infrastructure compose file
volumes:
  postgres-data:
  elasticsearch-data:
  redis-data:
  kafka-data:
  zookeeper-data: